spring:
  jmx:
    enabled: true
management:
  context-path: /admin
eureka:
  password: password
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0