spring:
  jmx:
    enabled: true
management:
  context-path: /admin
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://user:${eureka.password:password}@localhost:8899/eureka/
    availabilityZones:
      default: ${APPLICATION_DOMAIN:${DOMAIN:defaultZone}}
