spring:
  jmx:
    enabled: true
#management:
#  context-path: /admin
eureka:
  instance:
    cluster: DEFAULT
    leaseRenewalIntervalInSeconds: 10
#    statusPageUrlPath: /admin/info
#    healthCheckUrlPath: /admin/health
  client:
    region: default
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://user:${eureka.password:password}@localhost:8899/eureka/
    availabilityZones:
      default: ${APPLICATION_DOMAIN:${DOMAIN:defaultZone}}
services:
  auth:
    username: user
    password: password
turbine:
  aggregator:
    clusterConfig: AUTHSERVER,CONFIGSERVER,MONITOR,CLIENT,REGISTRATIONSERVER
  appConfig: authserver,configserver,monitor,client,registrationserver
