server:
  port: 8899
security:
  user:
    password: ${eureka.password}
spring:
  cloud:
    config:
      enabled: false
eureka:
  password: "{cipher}AQASRoQKHVD5vmBofA290SkHow1vqCiGS6b7yGkcKNiE+S80dyRO4IKLqAL+HO7GcqgTMxL3mX22NDyn0dZp+7A/uzazJKGKoO6ct3odKl3bqu5FqSMkVtCs9cisD6nDohAU8OZf3ROHZ4wiRucQKZdTfFOeeuHiXPRSHhvbCSEvbDrNxv8LqVNHSrT/S9oF20YrpbaMc59EYDx6MKcwFBqTKe+HHPbYKfNWw+iI/i4r6ZfRnmBqHDyFPuDufil2sJmIFokwfRaSv+1iTkIhuP8FALSWWMR9o+IcRnBpTI3hPvFpkX5IOkmi4JSEzy6N4Dt/UdHZ3KVujX2nS5W2i/KOvSWSIflXtOKte5wa5rsVNb0Kvds6Vz1G8eUCDvH6P28="
  domain: localhost
  instance:
    leaseRenewalIntervalInSeconds: 10
    hostname: localhost
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health
  client:
    serviceUrl:
      defaultZone: http://${eureka.domain}:${eureka.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
logging:
  file: logs/service-registration.log
